### ISSUE TITLE
Shape with inner and outer radius

### ISSUE THREAD

**Issue by AsimAl-Sofi** [djsilva99/heatrapy#39]
hi
I would like to use the package to calculate the underground cable heat distribution. However, I was not able to build the cable layers, i.e., how to create a shape with inner and outer radius?
Is that possible?

**Comment by djsilva99** [comment]
Hello

As far as I understand, you can change the material in two stages. Let's say that the 2D object is made of material_1. Then you can define the outer radius:
```
>>> example.change_material(
...     material='material_2',
...     shape='circle',
...     initial_point=(5, 5),
...     length=5
... )
```
and then the inner radius:
```
>>> example.change_material(
...     material='material_1',
...     shape='circle',
...     initial_point=(5, 5),
...     length=2
... )
```
This gives you a shell of thickness = 3.

**Comment by AsimAl-Sofi** [comment]
Thanks for the explanation
In the tutorial on the site, the circle does not look smooth. Is it also possible to increase the resolution of the added shapes?

**Comment by djsilva99** [comment]
Yes. When you instantiate a `SingleObject2D` you define the size attribute. There, you can increase it, e.g., from the default value of `(10, 10)` to `(100, 100)`. However, note that:
- you need to redefine some input values, such as `dx`, `dy` (reduce to keep the size) and `dt` (so that the solution can converge), and the corresponding parameters `length` and `initial_point` from the above `change_material` method.
- the size will impact the computation performance.

**Comment by AsimAl-Sofi** [comment]
Thank you for your explanation
